### ISSUE TITLE
Feature Request: Option to force cleanup of lock file upon unlock/release.

### ISSUE THREAD

**Issue by matthewlenz** [perlancar/perl-File-Flock-Retry#1]
Code:
```
#!/usr/bin/env perl

use File::Flock::Retry;

say $$;
my $lock = File::Flock::Retry->lock('/tmp/t.pl.lock', { retries => 0 });
sleep 30;
$lock->release;
```

This works just fine and the lock prevents another process from running as expected.

If this code is run and the process is killed before it finishes the lock file is left dangling.  Understandable.

If I run the same code again it works fine and the lock prevents another process from running.  But if I allow it to complete the lock file is still left dangling. 

An option such as:

remove => 1

This would still only fire if the lock was able to be acquired.

Would be useful for the rare situations where a process needs to be stopped in such a way that your cleanup code is unable to be run.

This might also prove useful for those using mode => O_CREAT | O_EXCL | O_RDWR

**Comment by perlancar** [comment]
Sorry for the very late response. I didn't see the notification for this issue.

I think this makes sense. I've changed the behavior (commit cb05e67) to delete even if the lock file was not created by the same process. But the lock file still needs to be empty.
